// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TEST1_SCADA.Data;

#nullable disable

namespace TEST1_SCADA.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MachineStatusRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Line")
                        .HasColumnType("int");

                    b.Property<string>("M1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("M2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("M3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("M4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("RawM1")
                        .HasColumnType("tinyint");

                    b.Property<byte>("RawM2")
                        .HasColumnType("tinyint");

                    b.Property<byte>("RawM3")
                        .HasColumnType("tinyint");

                    b.Property<byte>("RawM4")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.ToTable("MachineStatusRecords");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("TEST1_SCADA.Models.MonitorRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("CaSo")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Line")
                        .HasColumnType("int");

                    b.Property<int?>("M1_Empty")
                        .HasColumnType("int");

                    b.Property<int?>("M1_EmptyPct")
                        .HasColumnType("int");

                    b.Property<int?>("M1_Good")
                        .HasColumnType("int");

                    b.Property<int?>("M1_Jam")
                        .HasColumnType("int");

                    b.Property<int?>("M1_Oee")
                        .HasColumnType("int");

                    b.Property<int?>("M1_Speed")
                        .HasColumnType("int");

                    b.Property<int?>("M1_Stop5m")
                        .HasColumnType("int");

                    b.Property<int?>("M1_Stop5s")
                        .HasColumnType("int");

                    b.Property<int?>("M1_Total")
                        .HasColumnType("int");

                    b.Property<int?>("M2_Empty")
                        .HasColumnType("int");

                    b.Property<int?>("M2_EmptyPct")
                        .HasColumnType("int");

                    b.Property<int?>("M2_Good")
                        .HasColumnType("int");

                    b.Property<int?>("M2_Jam")
                        .HasColumnType("int");

                    b.Property<int?>("M2_Oee")
                        .HasColumnType("int");

                    b.Property<int?>("M2_Speed")
                        .HasColumnType("int");

                    b.Property<int?>("M2_Stop5m")
                        .HasColumnType("int");

                    b.Property<int?>("M2_Stop5s")
                        .HasColumnType("int");

                    b.Property<int?>("M2_Total")
                        .HasColumnType("int");

                    b.Property<int?>("M3_Empty")
                        .HasColumnType("int");

                    b.Property<int?>("M3_EmptyPct")
                        .HasColumnType("int");

                    b.Property<int?>("M3_Good")
                        .HasColumnType("int");

                    b.Property<int?>("M3_Jam")
                        .HasColumnType("int");

                    b.Property<int?>("M3_Oee")
                        .HasColumnType("int");

                    b.Property<int?>("M3_Speed")
                        .HasColumnType("int");

                    b.Property<int?>("M3_Stop5m")
                        .HasColumnType("int");

                    b.Property<int?>("M3_Stop5s")
                        .HasColumnType("int");

                    b.Property<int?>("M3_Total")
                        .HasColumnType("int");

                    b.Property<int?>("M4_Empty")
                        .HasColumnType("int");

                    b.Property<int?>("M4_EmptyPct")
                        .HasColumnType("int");

                    b.Property<int?>("M4_Good")
                        .HasColumnType("int");

                    b.Property<int?>("M4_Jam")
                        .HasColumnType("int");

                    b.Property<int?>("M4_Oee")
                        .HasColumnType("int");

                    b.Property<int?>("M4_Speed")
                        .HasColumnType("int");

                    b.Property<int?>("M4_Stop5m")
                        .HasColumnType("int");

                    b.Property<int?>("M4_Stop5s")
                        .HasColumnType("int");

                    b.Property<int?>("M4_Total")
                        .HasColumnType("int");

                    b.Property<int>("Machine")
                        .HasColumnType("int");

                    b.Property<int>("PollMs")
                        .HasColumnType("int");

                    b.Property<int?>("SanPhamId")
                        .HasColumnType("int");

                    b.Property<int?>("TruongCaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SanPhamId");

                    b.HasIndex("TruongCaId");

                    b.ToTable("MonitorRecords");
                });

            modelBuilder.Entity("TEST1_SCADA.Models.ParameterSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ca")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("CaiDatThamSo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("MaSanPham")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SanPhamId")
                        .HasColumnType("int");

                    b.Property<string>("TenDayChuyen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenMay")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenSanPham")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ThoiGianCapNhatTuPLC")
                        .HasColumnType("int");

                    b.Property<int?>("ThoiGianChapNhanGoi")
                        .HasColumnType("int");

                    b.Property<int?>("ThoiGianDayGoiCan")
                        .HasColumnType("int");

                    b.Property<int?>("ThoiGianDungMay")
                        .HasColumnType("int");

                    b.Property<int?>("ThoiGianGoiCan")
                        .HasColumnType("int");

                    b.Property<int?>("TocDoChuan")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ParameterSettings");
                });

            modelBuilder.Entity("TEST1_SCADA.Models.ProductionInput", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CaSo")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DayChuyen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgaySanXuat")
                        .HasColumnType("datetime2");

                    b.Property<int>("SanLuongThuc")
                        .HasColumnType("int");

                    b.Property<int>("SanPhamId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ProductionInputs");
                });

            modelBuilder.Entity("TEST1_SCADA.Models.ReportRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("A")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CaSo")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("EmptyPct")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FaultPct")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Line")
                        .HasColumnType("int");

                    b.Property<decimal>("MTBF")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MTTR")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Machine")
                        .HasColumnType("int");

                    b.Property<decimal>("MinorStopPct")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("NgayBaoCao")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("OEE1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OEE2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OEE3")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("P")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Q")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SpeedLossPct")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SpicePct")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("StopPct")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Vtb")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("ReportRecords");
                });

            modelBuilder.Entity("TEST1_SCADA.Models.SanPham", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MaSanPham")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenSanPham")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SanPham");
                });

            modelBuilder.Entity("TEST1_SCADA.Models.ShiftConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CaSo")
                        .HasColumnType("int");

                    b.Property<int>("GioBatDau")
                        .HasColumnType("int");

                    b.Property<int>("PhutBatDau")
                        .HasColumnType("int");

                    b.Property<int>("TruongCaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ShiftConfigs");
                });

            modelBuilder.Entity("TEST1_SCADA.Models.TruongCa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("HovaTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaTruongCa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TruongCa");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TEST1_SCADA.Models.MonitorRecord", b =>
                {
                    b.HasOne("TEST1_SCADA.Models.SanPham", "SanPham")
                        .WithMany()
                        .HasForeignKey("SanPhamId");

                    b.HasOne("TEST1_SCADA.Models.TruongCa", "TruongCa")
                        .WithMany()
                        .HasForeignKey("TruongCaId");

                    b.Navigation("SanPham");

                    b.Navigation("TruongCa");
                });
#pragma warning restore 612, 618
        }
    }
}
