
CREATE TABLE SanPham (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    MaSanPham NVARCHAR(50) NOT NULL,
    TenSanPham NVARCHAR(100) NOT NULL
);

CREATE TABLE TruongCa (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    MaTruongCa NVARCHAR(50) NOT NULL,
    HovaTen NVARCHAR(100) NOT NULL
);
